config/routes.rb
Rails.application.routes.draw do
  get 'charges/index'
  
  resources :charges

  root 'charges#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

	def index
	end

	rescue_from Stripe::CardError, with: :catch_exception
  def new
  end

  def create
  # Amount in cents
  @amount = 500

  customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Rails Stripe customer',
    :currency    => 'usd'
  )
  end	
  
  def catch_exception(exception)
    flash[:error] = exception.message
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/index.html.erb
<h1>Stripe</h1>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
<article>
  <% if flash[:error].present? %>
  <div id="error_explanation">
    <p><%= flash[:error] %></p>
  </div>
  <% end %>
  <label class="amount">
      <span>Amount: $5.00</span>
    </label>
</article>
<script src="https://js.stripe.com/v2/"></script>
<script>
    Stripe.setPublishableKey('pk_test_8tDsyhfYkYrapqB9JHQIYRL2');
</script>
<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
  data-description="A month's subscription"
  data-amount="500"
  data-locale="auto"></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stripe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.stripe.com/v2/"></script>
    <script>
      Stripe.setPublishableKey('pk_test_8tDsyhfYkYrapqB9JHQIYRL2');
    </script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>